### ISSUE TITLE
Binary split of compound categories when finding the best split

### ISSUE THREAD

**Issue by nikhilsaharan33** [Rambatino/CHAID#142]
Kass (1980) mentions the following steps for the CHAID algorithm:

Step 1. For each predictor in turn, cross-tabulate the categories of the predictor with the
categories of the dependent variable and do steps 2 and 3.

    Step 2. Find the pair of categories of the predictor (only considering allowable pairs as
    determined by the type of the predictor) whose 2 x d sub-table is least significantly
    different. If this significance does not reach a critical value, merge the two
    categories, consider this merger as a single compound category, and repeat this
    step.

    Step 3. For each compound category consisting of three or more of the original
    categories, find the most significant binary split (constrained by the type of the
    predictor) into which the merger may be resolved. If the significance is beyond a
    critical value, implement the split and return to step 2.

Step 4. Calculate the significance (to be discussed later) of each optimally merged predictor,
and isolate the most significant one. If this significance is greater than a criterion value,
subdivide the data according to the (merged) categories of the chosen predictor.

Step 5. For each partition of the data that has not yet been analysed, return to step 1. This step
may be modified by excluding from further analysis partitions with a small number of
observation.
 
I wanted to know which part of your code implements Step 3. I checked your `stats.py` file for finding best split but could not find the implementation of step 3. It would be really helpful if this information can be provided. Thanks!

**Comment by Rambatino** [comment]
Hi @nikhilsaharan33 it's been a very long time since I've looked at any of this code.

Feel free to add it and I can review, but it may affect unit test assertions. If you look at the tests it should be relatively trivial to add that and see the impact. Given that we didn't follow the steps listed there and followed the IBM specification it may be that we solve that particular issue by doing all comparisons rather than iteratively building up groups and splitting. But I can't be too sure as it's been a long time.

What I would recommend doing is finding a use-case that isn't correct for this implementation given that the propensity of this algorithm to not follow step 3 and we can discuss there. But it may be that it's not possible.
